=== api-evangelist/apis-io/json-schema/apis-io-search-api-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/apis-io/refs/heads/main/json-schema/apis-io-search-api-schema.json",
  "title": "API",
  "description": "The description of the API",
  "required": [
    "name",
    "description",
    "image",
    "baseURL",
    "humanURL",
    "properties",
    "contact"
  ],
  "properties": {
    "name": {
      "type": "string",
      "description": "name",
      "minLength": 5
    },
    "description": {
      "type": "string",
      "description": "description of the API",
      "minLength": 5
    },
    "image": {
      "type": "string",
      "description": "URL of an image representing the API"
    },
    "baseURL": {
      "type": "string",
      "pattern": "^(http)|(https)://(.*)$",
      "description": "baseURL"
    },
    "humanURL": {
      "type": "string",
      "pattern": "^(http)|(https)://(.*)$",
      "description": "humanURL"
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string",
        "minLength": 1
      },
      "description": "tags to describe the API"
    },
    "properties": {
      "type": "array",
      "items": {
        "$ref": "#/components/schemas/Property"
      },
      "description": "URLs"
    },
    "contact": {
      "type": "array",
      "items": {
        "$ref": "#/components/schemas/Contact"
      },
      "description": "Contact to reach if questions about API"
    },
    "meta": {
      "type": "array",
      "items": {
        "$ref": "#/components/schemas/metaInformation"
      }
    }
  },
  "type": "object"
}

=== api-evangelist/apis-io/examples/apis-io-search-api-example.json
{
  "name": "Example API",
  "description": "An example API for demonstrating APIs.io",
  "image": "example-value",
  "baseURL": "https://apis.io/example",
  "humanURL": "https://apis.io/example",
  "tags": [
    "payments"
  ],
  "properties": [
    "example-value"
  ],
  "contact": [
    "example-value"
  ],
  "meta": [
    "example-value"
  ]
}
